message:
  service:
    url: http://localhost:8033

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserInfo
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas:
      - app_schema
    baseline-on-migrate: true

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none

server:
  port: 8031

logging:
  level:
    org.flywaydb: DEBUG