spring:
  mail:
      host: smtp.yandex.ru
      port: 465
      username: markmessanger@yandex.ru
      password: zpmqfaumfymfwcpx
      properties:
        mail:
          smtp:
            auth: true
            ssl:
              enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/UserAuth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas:
      - app_schema
    baseline-on-migrate: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8030

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.mail: DEBUG
    org.eclipse.angus.mail: DEBUG