CREATE SCHEMA IF NOT EXISTS app_schema;

CREATE TABLE IF NOT EXISTS app_schema.messages(
    id SERIAL PRIMARY KEY,
    c_senderid BIGINT NOT NULL,
    c_chatid BIGINT NOT NULL,
    c_type VARCHAR(4) NOT NULL,
    c_text VARCHAR(400),
    c_img VARCHAR,
    c_sendtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)